### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#1]
Hello,

You got some build errors

h264sampleprovider.h(38): error C3668: 'FFmpegInterop::H264SampleProvider::WriteAVPacketToStream': method with override specifier 'override' did not override any base class methods (compiling source file ..\..\Source\H264SampleProvider.cpp)

error C2661: 'FFmpegInterop::MediaSampleProvider::MediaSampleProvider': no overloaded function takes 3 arguments

h264sampleprovider.cpp(48): error C2039: 'WriteAVPacketToStream': is not a member of 'FFmpegInterop::MediaSampleProvider'
mediasampleprovider.h(36): note: see declaration of 'FFmpegInterop::MediaSampleProvider'

**Comment by lukasf** [comment]
Have you perhaps been looking at the "experimental" branch? That one is old. Please check the master branch, it contains the refactored sources.

**Comment by mcosmin222** [comment]
I checked out master.
Are you sur you pushed all your latest changes?

**Comment by lukasf** [comment]
Strange. H264SampleProvider is not even part of the repo. 
Did you open the Windows 10 Solution?

**Comment by lukasf** [comment]
If I browse source on github, I also don't see that file...

**Comment by mcosmin222** [comment]
Yes. Windows 10 sol.

**Comment by mcosmin222** [comment]
Yes, you are right. Git did some strange merging on my repository.

**Comment by lukasf** [comment]
Closing this...
