### ISSUE TITLE
Config class: Default values?

### ISSUE THREAD

**Issue by lukasf** [lukasf/FFmpegInterop#12]
Currently, some passthrough options are enabled by default, others are disabled. I have been thinking if it is maybe better to disable all passthrough by default. Then the dev can explicitly decide which options to enable and which not. Some platforms might have HW acceleration for certain formats, others don't. Audio passthrough could make sense for phones which often have HW decoders, but PCs it does not really make sense. HW accelerated video depends on platform and hardware.

What do you think? Also the other default valuses, do they make sense?

**Comment by mcosmin222** [comment]
I think video pass through should be enabled by default.
Audio passthrough should be disabled by default (otherwise filters will not work, and besides, audio is really light).

We could put MaxSupportedPlaybackRate in there as well.

**Comment by lukasf** [comment]
Good point. Maybe add BufferTime as well.

**Comment by mcosmin222** [comment]
BufferTime should stay 0.

**Comment by lukasf** [comment]
Closing this...
