### ISSUE TITLE
Test Report 2

### ISSUE THREAD

**Issue by MouriNaruto** [lukasf/FFmpegInterop#15]
In several days ago, I have used "lyuv Video Output" and found the performance was not improved.

I had told in the "Test Report" issue, but @lukasf  said "And as you can see, there is almost zero CPU time spent in our code anymore with iyuv. So I didn't have any more convincing evidence to contradict. 

Until yesterday, I'm wondering if performance hasn't changed because the Windows Runtime API layer will help you convert the output format.
So today, I tested via the Performance Profiler and generated the detail report.

So my guess was validated. Please look at the screenshot.
![videopassthroughcpuperformance](https://user-images.githubusercontent.com/10867563/36582125-2bc1c16c-18ab-11e8-8fd2-9ce688b4f0b8.png)

Play the same video, output format convertion uses 24.68% of CPU time. The CPU time is three times more than using the sws_scale. (The sws_scale only uses about 8% of CPU time.)

So I was removing video passthrough implementations in my fork is a wise choice.

What do you think about that?

Mouri

**Comment by lukasf** [comment]
You do not need to remove the code. In the config class, Iyuv output is disabled by default, so it will not be used, unless you explicitly enable it. When I implemented Iyuv mode, I found performance was better compared to NV12 with sws_scale. Then we found out that for some formats, the wrong color range was used. When I added color range information to sample format, I found that this takes a considerable hit on performance, so for those files, performance was worse, compared to sws_scale. My guess is that sws_scale does conversion and color range correction in one go, while MF seems to do this ineffective, maybe processing data twice.

You can try to disable the following code, and see if Iyuv performance improves:

```
if (m_OutputPixelFormat == AV_PIX_FMT_YUVJ420P)
	{
		// YUVJ420P uses full range values
		videoProperties->Properties->Insert(MF_MT_VIDEO_NOMINAL_RANGE, (uint32)MFNominalRange_0_255);
	}
```

MPC-HC just ignores color range and outputs the image with wrong color range. I tought about making color range correction optional, to allow performance tweaks. At least in my testing a while back, Iyuv without color range correction gave lowest CPU usage.

**Comment by lukasf** [comment]
By the way, the video file is coming now, slowly, seems DHT has found some source. I will let you know once I received and tested it.

**Comment by MouriNaruto** [comment]
It is only need a buffer copy if we use the sws_scale.
But if we use the passthrough, MF will convert output format before the buffer copy.

My Windows version is 16299.248

**Comment by lukasf** [comment]
Oh, really? For my files, CPU usage went down from 75% to 65% when disabling that code. Well, maybe things also depend on the system or whatever.

By the way, the video file is coming now, slowly, seems DHT has found some source. I will let you know once I received and tested it.

**Comment by MouriNaruto** [comment]
Got, thanks.

**Comment by lukasf** [comment]
I have been able to test with your 120fps file. And you know what? Surprisingly, I get totally different results! For me, FFmpegInterop is by far the fastest decoder. It only uses 30-40% CPU and about 55% GPU. Absolutely fluid playback. MPC-HC uses 70-80% CPU and 75% GPU, but manages fluid playback. PotPlayer is worst. It stutters and is often at 80-90% CPU, GPU also over 80%.

These are the results with ffmpeg 3.4.2. I also tested with the older ffmpeg 3.3.2 and it had about 5% higher CPU usage, still, it was by far the fastest of the pack.

Well, I am really a bit surprised by the results. Which ffmpeg version are you using? I can only recommend you to try ffmpeg 3.4.2, maybe it will improve performance for you as well. Maybe things are just very much dependend on the system, hardware, drivers, whatever. I have also seen FFmpegInterop being the fastest with other files as well, as I wrote previously. Maybe it just works very well with my system.

**Comment by lukasf** [comment]
Adding to that, maybe it is clear, but if you want to see real world performance, you always must test with "Release" build and without debugger. If you have debugger or performance profiler attached, performance will be a lot worse than normal. And debug builds are obviously also pretty bad, performance wise.

**Comment by MouriNaruto** [comment]
I tested it with the FFmpeg 3.4.2. Of course, the Release(x86) version.
My PC Hardware is: Xeon E3 1230 V2 + 8GB DDR3 1333 x2 + GTX760 + 256GB SSD

What's your hardware system, and I want to know the FFmpeg configure parameter which you are using.

My FFmpeg configuration: https://github.com/M2Team/FFmpegUniversal

**Comment by MouriNaruto** [comment]
I also want to make a suggestion.

How about using the C++/WinRT after the RedStone 4 released?

**Comment by MouriNaruto** [comment]
Also, I want to make friends with you. 
Because it's not good to ask for your email address here, if you also want to make friends with me, please email to Mouri_Naruto@Outlook.com  (This is my public email address.)

**Comment by lukasf** [comment]
My Laptop has a Core i7-7700HQ (8t 2.8-3.8GHz), 16GB RAM (dual channel) and GTX 1050 (but test was run with iGPU). Now I was just thinking, what kind of display do you use? I tested on my 60Hz laptop display. Maybe things would look different on a 120Hz display. But I don't have such a display.

Yes I took some inspiration from your build files. Especially the part for finding the VS installation folder was shamelessly stolen ;) Still it was quite a struggle to get this running correctly, but in the end I figured it out. I built ffmpeg 3.4.2 with that new file, 3.3.2 was build with the older VS2015 files. You are using some different options in your build configuration, I cannot say if that makes a difference.

I really like C++/WinRT form what i have seen. I have not used it yet, it looks very promising. But I don't know if I'd start rewriting the code from C++/CX to C++/WinRT. I'd probably use it next time I start a new WinRT project, to get some experience with that.

**Comment by MouriNaruto** [comment]
Got.

If I remember correctly, starting with the 7th gen Intel CPU's GPU can use hardware decoding to play this kind of video. (Intel GPU is really good at hardware video decoding,)

Of course you can reference my script implementation without notice me. (I think no people will be helped until see your reply because my script has no GitHub stars. Thank you for referencing it.)

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/Violet
This is my fork repo I mentioned before. I removed the hardware decoding and passthrough. (Make better performance on my Desktop PC.)

PS: My Desktop PC has no iGPUs, only a Nvidia Kepler GPU.

**Comment by lukasf** [comment]
All testing was done without hardware acceleration or IYuv passthrough. With hardware decoding, I only have ~3% CPU usage. IYuv did not improve performance for me with this file, so I left it disabled.

As I said before, you do not need to remove passthrough or HW acceleration code. If the config flags are set to false, the code paths will not be used. You will not get any better performance by removing code that is not used.

And by the way, why would you want to remove HW acceleration? It is ok to disable it for testing SW decoding performance. But you surely would not want your app to use SW decoding when HW acceleration is available.

**Comment by MouriNaruto** [comment]
Because I want to make a smaller binary.

HW decoding is good, but the FFmpegInterop don't know the HW decoder's limit. In some cases beyond the coding limit of the screen will be problematic (I use HW decoder in this video in my PC hard solution will lose frames)

**Comment by MouriNaruto** [comment]
Even using the SW decoder, with the new CPU instruction sets in fact the CPU usage is smaller than I think (1080p 10%), so it removed.

**Comment by MouriNaruto** [comment]
Using the HW decoder in MPC-HC is enabled by default, so playing my test video without setting on my PC will cause problems.

There is no problem in PotPlayer because it uses the SW decoder by default.

**Comment by lukasf** [comment]
Well, I don't know what your scenario is. But if this is intended for general use (and not just a private project running on your specific devide), then it would be better to leave HW acceleration in place and have a setting in the options, so users can enable and disable it. For almost all users it will be better to have HW acceleration enabled, if they have a compatible (i)GPU.

The ffmpeg dlls alone are 16-21mb per platform. The size of the FFmpegInterop.dll is very small in comparison, no matter if it conains passthrough code or not. You can of course fork and remove code, if you think it is a good idea. But you will have to manually keep your fork up-to-date, and probably run into merge conflicts every now and then. I would not want to do that, if the only benefit is saving a few KBs (of a multi MB project).

**Comment by MouriNaruto** [comment]
Yes, sync code regularly is a chore.

I merge the FFmpeg dlls in one FFmpeg dll in my compile configuration. 
It makes the folder neat, I don;t like plenty of dlls in my app's folder.

But for compatibility, I recommend that FFmpegInterop use software decoders by default.
Because no one knows what kind of video the user will play.

The user's choice is easily make us unexpected. A desktop application I've been involved in has received a feedback in recent years which is "Someone use this tool on PC with Pentium 3 CPU and find it crashed."

**Comment by MouriNaruto** [comment]
I am agree with you.

PS: If the project does not involve media encoding in the future, you can save space by disabling all encoders in the FFmpeg compilation script.

**Comment by lukasf** [comment]
That is a good idea. I will check how that improves file size in the 3.4.3 branch.

**Comment by MouriNaruto** [comment]
PS: I tested FFmpegInterop with GPLv3 mode of FFmpeg just now. No improvement.
