### ISSUE TITLE
Inconsistent line endings

### ISSUE THREAD

**Issue by lukasf** [lukasf/FFmpegInterop#19]
There are a lot of files where CR and CR/LF lines are mixed. Reason is that there is no .gitattributes file in place to enforce line endings. So line endings depends on user's local git configuration. Some devs probably have git core.autocrlf enabled, others have it disabled, which causes this mess. This leads to problems with merging, wrong file diffs (showing whole file as changed although only few lines were changed), warnings in VS.

We should add a .gitattributes file to enforce consistent line endings for the project, then fixup all files once.

**Comment by mcosmin222** [comment]
This seems to be fixed. I haven't had any warnings about line ending lately.

**Comment by lukasf** [comment]
I also have not observed this in quite some time. Please be sure to have core.autocrlf enabled in your git config. Closing this for now...
