### ISSUE TITLE
My english cartoons default to russian and other issues

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#21]
Hello again @lukasf 

Are you sure this is the best way of determining the default audio stream in a file?
```

auto audioStreamIndex = av_find_best_stream(avFormatCtx, AVMEDIA_TYPE_AUDIO, -1, -1, NULL, 0);
...
bool isDefault = index == audioStreamIndex;
```
Shouldn't we just default to stream 0?

**Comment by mcosmin222** [comment]
Bonus issue: when I switch the audio streams, video stops playing and starts buffering samples.

**Comment by lukasf** [comment]
Most file formats have a "default" flag for streams. The first stream is not neccessarily the default stream. Only if no "default" flag is found, the method will take the first stream. So yes, I do think that this is the correct way to do it.

It looks like we get a "OnStarting" call after a stream switch, that is why there is a short interruption (seek operation plus flush of buffers). We could try to skip that seek in case a SwitchStream has just happened. But we'd have to be sure to not accidentially skip other seek requests.

**Comment by mcosmin222** [comment]
Oh well, looks like my cartoon shop likes russian alot then 📦 

But still we have the 2nd problem, video stops after switching streams. Can you reproduce the sample or should I send over some cartoons?^^
