### ISSUE TITLE
Video stream incorrect timestamp after switching audio stream

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#22]
Before: 103440000
After:      57970000

This causes the video pause described in #21

**Comment by mcosmin222** [comment]
The thing is, in like 1% of trials this does work correctly, but most of the time video freeze, memory consumption goes up as the video samples are provided but not played.

**Comment by mcosmin222** [comment]
It looks like a null sample is sent in the video stream right after switching audio streams.

**Comment by lukasf** [comment]
What happens when you seek the file without switching steams? I'd guess it is more a problem of the seek request that follows steam switch. I do not see that problem with my files. 

However, a read error should lead to disabled steam, I wonder why that is not happening.

**Comment by mcosmin222** [comment]
the read error was misleading, hence why I deleted the comment.

So the timeline is as follows, after I change the audio stream in UI.

1) Starting request at position X.
2) Switch streams request
3) Starting request at same position X as before.
4) Sample requests for video stream quickly one after another until reaching EOF.

This is pretty much consistent. If after this I also do a normal seek, video samples are once again buffered but nothing is played.

**Comment by mcosmin222** [comment]
In case of normal seek everything is fine.it has something to do with the switch request.

**Comment by lukasf** [comment]
Can you upload one of the files? I'd really like to take a look. I tried several movies here and none shows the problem.

It is strange becuse ffmpeg does not even know when we switch streams. It's not like we tell it. The only thing that happens after stream switch on ffmpeg side is a seek request and a flush of the video decoder. But the same thing also happens during normal seek...

**Comment by mcosmin222** [comment]
The file is uploaded here: https://1drv.ms/f/s!Ao-WOwsImxSMttQ3J0LUSS91OnD4nw

**Comment by mcosmin222** [comment]
I just noticed that the audio streams are quite different. For example, I am pretty sure some 2 guys speaking in Russians are quite different than 2 people fighting. I don't think we are doing the FFMPEG seeking correctly.

**Comment by lukasf** [comment]
I do not have any problems switching streams with that file. Are you perhaps using an unofficial ffmpeg version (master branch)? With 3.4.2 I do not seem to have any issues.

**Comment by mcosmin222** [comment]
What OS version are you using?

**Comment by lukasf** [comment]
Windows 10 x64 16299

**Comment by lukasf** [comment]
One thing you could try is skip the next seek operation after a stream switch. Then the video should continue without interruptions. But there will probably be a short time without audio, depending on how the file is muxed. I think audio is usually muxed ~2 seconds before video, but there could also be a larger gap, which would be undesirable.

**Comment by lukasf** [comment]
Did you also test with the sample app? Same problem there?

**Comment by mcosmin222** [comment]
@lukasf I already tried skipping the seek operation and it did not do the trick.

I just recompiled ffmpeg from 3.4.2 mirror, same problem >.<

I will give the sample app a try.

**Comment by mcosmin222** [comment]
OK I admit you were right. I recompiled ffmpeg and only after a **clean** deploy of my app did it work. But the sample still doesn't.

**Comment by mcosmin222** [comment]
OK, so it is got something to do with compressed samples.

**Comment by mcosmin222** [comment]
@lukasf another strange thing is that even if i force them code to use our custom timeline tracking (behave as if packages did not have a presentation timestamp), the same issue occurs. I am still not sure where we are doing wrong, if it is our doing at all - looks like some shady ffmpeg stuff. Have you managed to reproduce the issue?

**Comment by lukasf** [comment]
Somehow I thought you were using software decoding, because of talk of NULL video samples, so I always set video passthough to false. When using passthrough, I got the same problem. I also found a few other files where this is happening for me (but most files were fine even with passthrough).

It was just a wild guess but somehow sending extradata again fixed the problem. Please check #23, I hope it fixes the problem for you as well.

**Comment by lukasf** [comment]
And I really need to be careful with those pull requests. Again did one on MS project.... :-S
