### ISSUE TITLE
visual studio 2017 build file wants MSYS2

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#28]
I cloned the repo and then tried to run the vs2017 bat file to build. and got the following error.
![image](https://user-images.githubusercontent.com/11542189/37461960-0a3285e6-2872-11e8-8691-2d27f0a86d97.png)

>Checking for MSYS2...

MSYS2 is needed. Set it up properly and provide the executable path in MSYS2_BIN environment variable. E.g.

    set MSYS2_BIN="C:\msys64\usr\bin\bash.exe"

do I still need to setup msys2 before I run the bat file?

**Comment by lukasf** [comment]
Yes you need to follow all the setup steps exactly from ffmpeg site. This is also written in our readme.md.

**Comment by touseefbsb** [comment]
the readme states that we can either run the build.bat file or we can follow the instructions of the compilation guide link, tht is why it is a bit confusing

**Comment by touseefbsb** [comment]
I think we need to complete all steps before **Compiling** in the CompilationGuide link. and after that run the bat file.

**Comment by touseefbsb** [comment]
I completed steps until **gas-preprocessor Setup** and then ran the bat file for vs 2017 and got following warning in both x86 and x64 builds at the end

**WARNING: pkg-config not found, library detection may fail.**

in the compilation guide link verification of environment seems to be with VS 2015 only. and not VS 2017.

**Comment by mcosmin222** [comment]
Ignore that warning.

**Comment by touseefbsb** [comment]
i got an output folder but no Build folder in ffmpeg

**Comment by lukasf** [comment]
You need to read and follow the readme completely. It starts with getting sources, installing ffmpeg build tools, building ffmpeg, only then comes the point building FFmpegInterop, which seems to be the point where you wanted to start. But I agree that the docs can still be improved.

You can run the link verification steps also from a VS2017 developer command prompt such as "ARM Cross Tools". Do you only have VS2017 installed?

**Comment by touseefbsb** [comment]
yes I only have VS 2017, though I have 2 versions of it, community and enterprise, but I guess tht doesnt make a difference?

**Comment by touseefbsb** [comment]
I cant find the ARM Cross Tools as per the location suggested in the compilation guide. I have "developer Command prompt for VS 2017" and then within a folder named **VC** I have x86 x64 cross tools, x64 x86 cross tolls ( and native tools as well ) but no **ARM Cross Tools**

**Comment by lukasf** [comment]
That's strange, but well, any kind of VS cmd tools should work.

**Comment by touseefbsb** [comment]
yeh thts why I tried to do the validation with x86 x64 cross tools and some elements were validated and some were absent.

**Comment by touseefbsb** [comment]
![image](https://user-images.githubusercontent.com/11542189/37473553-2e50b970-2890-11e8-84f2-c72e45cc4c49.png)

**Comment by mcosmin222** [comment]
@lukasf , no, you cannot use any of the VS command tools. If I use the wrong one, I get a "C compiler test failed".

@touseefbsb , reinstall Visual Studio from scratch - just one edition, I am not even sure why on earth you would want both enterprise and community editions, since there are no differences between them that you would feel.

**Comment by touseefbsb** [comment]
following commands are from compilation guide to validate.

$ which cl
/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_ARM/cl

$ which link
/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_ARM/link

$ which armasm
/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_ARM/armasm

$ which yasm
/usr/bin/yasm

$ which cpp
/usr/bin/cpp

$ which gas-preprocessor.pl
/usr/bin/gas-preprocessor.pl

as you can see some stuff is supposed to be present in program files/VS 14.0   folder, I double check this folder in my file explorer and I dont any a folder named **VC**

**Comment by touseefbsb** [comment]
well I initially installed community, and then installed enterprise bcz it has lot of features, most important being the reference track back for methods and classes makes life easier. but I am still much confused why it is so complicated to get this build, and not a simple nuget package, anyways, can I do all of this on a VM and then copy the built packages on my machine and use them? because installing VS from scratch might take a lot of time on my own PC.

**Comment by mcosmin222** [comment]
It is tricky because this involves a lot of tools being at the right place, so if you install several versions, you might create path conflicts without knowing it. So reinstall from scratch - just one edition.

**Comment by touseefbsb** [comment]
maybe there is some component to install within visual studio setup, needed to do all this, which I dont know about? because ok i can have path conflicts so I should have just 1 version, Ill remove the community version, but what I dont understand is, why I dont have the ARM cross tools?

**Comment by touseefbsb** [comment]
I remember that in the main repo ( the Microsoft one ) had a simpler way to compile for VS 2017, with about 4, 5 commands and it didnt involve a single step for compilation guide. following were the steps to get the packages in that repo.

git clone https://github.com/khouzam/vcpkg -b ffmpeg-uwp

cd vcpkg
bootstrap-vcpkg.bat

vcpkg install ffmpeg:x86-uwp ffmpeg:x64-uwp ffmpeg:arm-uwp

x86 and x64 packages build successfully, error occurred with arm package.

I wonder can we do the same in this repo?

**Comment by mcosmin222** [comment]
We need only 2 lines ...

**Comment by lukasf** [comment]
I'd also strongly recommend uninstalling the community edition if you already have enterprise.

I just checked at home, I also don't have ARM tools, looks like they are not delivered with VS2017 anymore. But you can create an ARM environment like this: Run normal cmd. Then enter the following:

```
C:\Users\lukas>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64_arm'

C:\Users\lukas>\msys64\msys2_shell.cmd
```

You will need to change the VS path. I am using VS2017 Professional, not Enterprise.

**Comment by lukasf** [comment]
Ah and about your other question: Yes it is possible to build ffmpeg on a different machine or VM and then copy over. After building, just copy the "Build" folder into FFmpegInterop\ffmpeg on the target machine. Now you can build FFmpegInterop.

**Comment by touseefbsb** [comment]
@lukasf  I followed ur instructions and opend the msys shell and again validated but got the same validation result as before. now should I run the build bat file again for visual studio 2017? in order to complete the compilation?

**Comment by touseefbsb** [comment]
if u look at the screenshot I posted above about the validation results, it shows I have both **yasm** and **preprocessor.pl** and in compilation guide before validation it asks us to download and place these 2 files into our msys2 folder so that makes sense, but it never tells to download or paste other things like **cl** **cpp** **armasm** **link** so that is why it cant find them on validation? although it does find link.

**Comment by touseefbsb** [comment]
and I have removed community version I only have enterprise version now

**Comment by touseefbsb** [comment]
@lukasf  yeah I followed all that and now verified all of them and getting all others, but the **armasm** and **cl** are still not found as I showed in the screenshot above.

**Comment by lukasf** [comment]
Did you run the command from a normal cmd? Running vcvarsall on a VS dev cmd does not work properly, it must be run from a normal cmd shell.

It it does not work when called from plain cmd, then I don't know, sorry. Something must be wrong with your VS installation. You could try building on a different machine or VM with clean VS2017 installation. Or uninstall and reinstall VS.

**Comment by lukasf** [comment]
If the validation does not succeed, then build will also fail. The build file uses the same vcvarsall call, and after that call, cl and armasm must be found.

**Comment by touseefbsb** [comment]
its strange bcz I had a sucesful build  as I told u , and I was able to run the sample app successfully, I even played a couple local video files with the sample app, and got no issues.

**Comment by lukasf** [comment]
I thought the builds failed? If the build was successful, then we can close this issue.

**Comment by touseefbsb** [comment]
yeah some validations were failing, but I went ahead with build.bat file for vs 2017 anyways, and then I got Build folder and was able to run the app successfully.

**Comment by touseefbsb** [comment]
@lukasf  when we have a complete build, do we still need the dll files within the MediaPlayerCS project? or can we delete them?
