### ISSUE TITLE
after build do we need the dll files in cs project?

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#35]
I was able to run the sample c# app, just out of curiosity wanted to ask, do we need the dll files within the c# project like avcodec, avdevice, .dll files? and also there is a languagetagconverter file, but I am guessing that is being used for subtitles? 
Or in other words wht do I need In order to use the library in my new c# project? do I need all the files exactly as in sample project, or do I just need a reference to ffmpeginterop project?

**Comment by lukasf** [comment]
You need the reference to the interop dll, plus all the .dll files from ffmpeg. The interop is only an adapter to easily use ffmpeg dlls from UWP. So you always need the ffmpeg dlls.

The LanguageTagConverter is not needed. I used this to initially generate the C++ code for tag conversion from a xml source file. I left the stuff in, so we could re-generate it again at a later time. It might be useful in future. But I think I will exclude it from the C# solution, to not cause confusion about it.

**Comment by mcosmin222** [comment]
Yes, you need the dlls in the cs project. They are used for dynamic runtime binding of the ffmpeg functions in the interop project.

**Comment by touseefbsb** [comment]
thnks guyx :)

**Comment by touseefbsb** [comment]
@lukasf  if you can clarify 2 other things as well please.
1. I tried added the ffmpeginterop project to another solution ( which was in another directory ), I did not copy pasted the ffmpeginterop project folder, ( just added it to the solution and then referenced it from my own c# uwp project within the same solution ) but my project still cant find "using FFmpegInterop" wht did I miss here?

2. I navigated to MediaPlayerCS project folder(in file explorer) and I can't see any dll files, how should I include those ddll files in my own project?

**Comment by lukasf** [comment]
1. I use the same setup and it works for me. Please note that you cannot use FFmpegInterop in a "AnyCPU" configuration. You must define and use x86, x64 and ARM if you reference native code. Delete AnyCPU if it is there. If it still does not work, check Build->ConfigurationManager and make sure that FFmpegInterop is selected in your build configuration.

2. Please check the sample's .csproj file. It has the following content defined:

 ```xml
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\avcodec-57.dll" />
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\avdevice-57.dll" />
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\avfilter-6.dll" />
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\avformat-57.dll" />
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\avutil-55.dll" />
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\swresample-2.dll" />
    <Content Include="$(SolutionDir)ffmpeg\Build\Windows10\$(PlatformTarget)\bin\swscale-4.dll" />
```

You need to add this to your own .csproj file. You have to adapt the path according to your directory structure, maybe have it start like this: $(SolutionDir)..\FFmpegInterop\ffmpeg. The $(PlatformTarget) will make sure that you get the right native DLLs for the selected platform.

**Comment by touseefbsb** [comment]
I see so basically I need to copy everything in my own solution as well so that I can reference them with these paths?

**Comment by mcosmin222** [comment]
Yes, that would be preferable. 
You can simply rename the solution from the sample and build your app on top of it, since it has all the configs done. I went through the pain of creating my own solution and in the end it wasn't really worth it, just for custom folder structure.

**Comment by touseefbsb** [comment]
@mcosmin222  actually I have my repo hosted in visual studio team services hence I have a gitignore file as well I am just worried about the difference between the two files and how to solve that, and whethr I should delete my own gitignorefile , because its just  auto generated for uwp projects

**Comment by lukasf** [comment]
I have my solution next to FFmpegInterop and as I said, I had zero problems with that. No conflicts, no .gitignore problems, no false checkins when working on either my app or ffmpeginterop. The only change you need to do is paste the dll references into your .csproj as noted above, and change path to ffmpeg in these definitions. That's all. 

Previously there was more work required for having parallel solutions, but I have already fixed that, so you only need the dll references.

**Comment by touseefbsb** [comment]
I managed to solve it, I copied all stuff ( apart from git files ) to my repo and now everything is working perfect :)
