### ISSUE TITLE
AvFormatContext start_time

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#38]
The correct check at line 43 in MediaSampleProvider is this

if (m_pAvFormatCtx->start_time != AV_NOPTS_VALUE)

And not this

if (m_pAvFormatCtx->start_time != 0)

I discovered this while inspecting some of the more weird audio files I encountered.

Created PR #37 for this

**Comment by lukasf** [comment]
Oh ok, you actually observed this in files? The docs do not mention this for AVFormatContext (only for AVStream) and I always saw this being 0 when no offset is used. But if it can occur, we definitley need to take care of it.
