### ISSUE TITLE
wack tests failed

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#39]
ok guyx so I submitted my app to the store and got the certification failed with following errors. 

Error Found: 
The supported APIs test detected the following errors:
API __C_specific_handler in vcruntime140.dll is not supported for this application type. avdevice-57.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. avdevice-57.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. avdevice-57.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. avdevice-57.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. avdevice-57.dll calls this API.

**Comment by touseefbsb** [comment]
this error has also occurred in the original ffmpeginterop repo as well, but the fix there is not quite clear. https://github.com/Microsoft/FFmpegInterop/issues/190

**Comment by mcosmin222** [comment]
Which package fails the test?

**Comment by touseefbsb** [comment]
@mcosmin222  you have a working build, can you please do me a favor and send me the Build folder of your ffmpeg folder? I think tht might solve this issue, bcz as per other issue on other repo this problem is within the ffmpeg build, and I used the VS 2017 bat file to build mine, everything ran perfectly, only the wack test is failing, its strange that's its not occurring to everybody, makes it harder to recognize the problem.

**Comment by touseefbsb** [comment]
I wish we can have a system where we can keep getting built nuget packages for stable releases of the repo and if someone wants prerelease they can build it themselves from this package. all the documentation to build this is totally outdated from start to finish, that compilation guide, is very old and talks abt vs 2013, and vs 2015, and the some tools in the process don't even come anymore with vs 2017.

**Comment by mcosmin222** [comment]
Does the test fail on Store or when you run the wack manually?

**Comment by touseefbsb** [comment]
both places

**Comment by touseefbsb** [comment]
@mcosmin222  Did u also build with VS 2017.bt file of this repo?

**Comment by touseefbsb** [comment]
why is that ? wht is different in case of ARM?

**Comment by touseefbsb** [comment]
@lukasf  you said that a build on one pc can work fine on another pc, would you be willing to provide me with the build which is passing the wach certification? this error seem to happen only rarely so there isnt any solution for this uptil now sadly.

**Comment by mcosmin222** [comment]
I used the different script for ARM because the VS2017 script would cause a dll not found exception on windows 10 mobile, and at that time I didn't have the time to debug and see what was wrong, because I had to push the update quickly.

**Comment by lukasf** [comment]
Maybe the VS2017 build script is not good. It might be that I have to set the UWP target version in the build setup. Unfortunately, I have a problem with my PC right now. WACK always reports "test execution blocked, please retry" on 70% of all tests including API test. Installed latest VS update, rebooted, no luck.

**Comment by touseefbsb** [comment]
@lukasf  did u try stackoverflowing this problem ?or maybe try reinstall VS? ( I know thts a lot of pain though )

**Comment by touseefbsb** [comment]
yeah I also guessed the same , maybe u need to add those 3 steps to the vs 2017 build file to define x86, x64 and arm targets.

**Comment by mcosmin222** [comment]
everything works fine for me, I use WACK 16299.15

Windows build 17134

**Comment by touseefbsb** [comment]
I am also on insider build. strange tht it works for u and not for me

**Comment by lukasf** [comment]
I am using latest WACK plus latest official Windows version. There is not a single google hit for the error message I get (unfortunately I get a german localized error message).

@touseefbsb Did you use an official ffmpeg version (3.3 or 3.4 tag) when you built ffmpeg? If you use "latest", you might run into problems.

**Comment by lukasf** [comment]
Then you should be on an official version. The FFmpegInterop project already includes an approved ffmpeg submodule. It is strange that you get API warnings and @mcosmin222 does not get them.

Some people pulled latest changes from ffmpeg master branch, and then got build errors or warnings. This is not recommended. You should always use the ffmpeg version that comes with FFmpegInterop, and not update the ffmpeg repo manually to an unofficial ffmpeg build.

**Comment by touseefbsb** [comment]
yeah I did not update manually, btw I tried the folder given by @mcosmin222  and my local wack tests were passed, but since then I've resubmitted to the store and now they are taking forever in certification, so I stll dont know whether they will approve it this time or not, but it certainly is taking a lot longer than last 2 times ( when it failed )

**Comment by lukasf** [comment]
The certification taking longer (while being annoying) could be a good sign, so the automatic API tests are probably already passed...

**Comment by touseefbsb** [comment]
I am also thinking the same that it is probably going to pass this time

**Comment by mcosmin222** [comment]
My libs works because I built them a few months ago. For that matter, I do not keep the latest ffmpeg unless there is some broken bug in it that requires an update.

**Comment by touseefbsb** [comment]
I am curious @mcosmin222  which command prompt did u use to execute "VS2017.bat" file? I used the normal command prompt, I guess u used a command prompt from vs 2017  ? which automatically created the required environment variables before the build started?

**Comment by touseefbsb** [comment]
@lukasf  thanks for clarification, atleast its good news that if @mcosmin222  packages work for me, then I'll be able to keep using them because ffmpegintrop repo can update independent of ffmpeg builds, so I can keep using this repo, but it would be ideal if we are able to get to the root of this problem.

**Comment by khouzam** [comment]
Hi @touseefbsb 

Can you share your exact build steps?

**Comment by lukasf** [comment]
@touseefbsb Have you tried to rebuild ffmpeg using the same steps and then rebuild your app and run WACK?

Also can you check the "Changelog" file in ffmpeg folder? It should start like this:

> Entries are sorted chronologically from oldest to youngest within each release,
> releases are sorted from youngest to oldest.
> 
> version 3.4.2:
> ...

**Comment by touseefbsb** [comment]
@lukasf  yes I do see the changelog file and version is 3.4.2 should I upload the file here for u guyx to have a look ?

**Comment by lukasf** [comment]
@touseefbsb No that's fine. Just confirming that you are on recommended ffmpeg version.

**Comment by touseefbsb** [comment]
I will try a clean build again, I tried it before on another VM but was having some trouble installing yasm  , ill try it again on my own machine as well

**Comment by touseefbsb** [comment]
yeah the version seems fine, if I remember correctly I did have some warnings during my build, which we discussed on another issue I guess, but we ignored that because build was successful and I was able to run the app. the problem was during verification, not all components needed were verified on my machine. and then during build, I also got some warnings, 1 or 2 guess, but nothing major.

**Comment by lukasf** [comment]
I have updated the VS2017 build script to explicitly configure a UWP platform target. I used 10.0.15063.0 because that is what is used by the interop lib right now. The build machine must have the Windows 10 SDK 10.0.15063.0 for C++ installed to build ffmpeg with this script.

Maybe this will also solve the ARM target issue @mcosmin222 saw when using the VS2017 script.

You can try the new build script on branch "vs2017-build-script"

The updated build script worked fine for me, but I am still not able to run WACK. Same error on all apps I try, no matter if ffmpeg is involved or not. Gonna try VS re-installation next.

**Comment by lukasf** [comment]
I was finally able to run wack, and I get the same API warnings when I use the VS2017 script to build ffmpeg! But with the updated build script from vs-2017-build-script branch, the API test is passed. So it was indeed the uwp target that was missing (this was not required in VS2015).

So please try the updated build script, it should produce correct binaries now which pass wack.

**Comment by touseefbsb** [comment]
brilliant, @lukasf  I think we can close this issue, as you were able to confirm it is solved, I don't have time right now to double check on my machine, but I will reopen if I encounter this issue in future :)
