### ISSUE TITLE
FFmpeg 4.0 released

### ISSUE THREAD

**Issue by lukasf** [lukasf/FFmpegInterop#40]
Maybe you read the news already. FFmpeg 4.0 has just been released. I am not sure if it is a good idea to jump to the new version already, since it is a new major release. It might be better to wait a while and see how things develop.

I will be on a 4 week vacation very soon, so I won't have time for quick actions anyways. If someone wants to take a look, please post your findings here. I think there have been some deprecations around lock_manager, maybe more. Supporting this would require some potential breaking changes from our side, so an updated FFmpegInterop would perhaps not work with older ffmpeg builds.

**Comment by mcosmin222** [comment]
The list of deprecation is here

https://github.com/FFmpeg/FFmpeg/blob/ec8a5262b03f85158d722dbc8b8f30cb6bd67e0f/doc/APIchanges

highlight "deprecate".

basic lock_manager seems to be built-in now.

I've seen the deprecated avfilter_register_all, and the avcodec_register_all and similar APIs. It doesn't look _that_ bad.

**Comment by MouriNaruto** [comment]
Starting from FFmpeg 4.0, it is the first time that we can build ARM64 libraries successfully.

Here is link the All-In-One dll for FFmpeg 4.0 made by me. (x86, AMD64, ARM and ARM64)
https://github.com/M2Team/FFmpegUniversal/releases/tag/4.0

I will rewrite this fork via C++/WinRT recently.

Mouri

**Comment by lukasf** [comment]
Ok, bitmap subs has been merged, good to go for ffmpeg 4.0!

**Comment by MouriNaruto** [comment]
@lukasf Yes

But the important thing I want to tell you is you can start to prepare the ARM64 support.
I hope configure parameters in my project can help you.

**Comment by mcosmin222** [comment]
@lukasf , thanks for the merge, I will make the branch during this weekend.

**Comment by mcosmin222** [comment]
We have PR #45 for this.

**Comment by lukasf** [comment]
PR is merged.
