### ISSUE TITLE
Encode Video for Live streaming

### ISSUE THREAD

**Issue by ramtinak** [lukasf/FFmpegInterop#43]
Hi,
It's not an issue, but I don't know anybody knows uwp, except you guys.

Recently I created a instagram client, I want to add live broadcasting via rtmp,
after sending 2 request to Instagram api, it will give an RTMP url.
But I don't know how to encode an live video stream to flv and keep sending this stream to RTMP Url.

Thanks.

@lukasf @mcosmin222

**Comment by mcosmin222** [comment]
Hi,

You should be able to use this MediaStreamSource for transcoding. You will need to create a MediaEncodingProfile for your desired output and you should be ready to go.

As for the streaming part, my guess is that you need to open a socket to the URL address and start sending data. You should probably look for some nuget to do this.

**Comment by mcosmin222** [comment]
Sorry. wrong thread (that replay I deleted :) )

**Comment by ramtinak** [comment]
Hi, @mcosmin222  Thanks for reply.
I can work with the part of MediaEncodingProfile and MediaStreamSource.

the problem is I didn't find anything to sending bytes/stream to that rtmp upload url.
if you can give me a code,link, todo.

thanks.

**Comment by mcosmin222** [comment]
I think you can use stream sockets for that. I'd expect the data package you send must have a specific format.

You can find the protocol specs here

https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol

and here

https://www.adobe.com/devnet/rtmp.html

I also found this, which is .net core. 

https://github.com/hinaria/rtmp-sharp

Sadly, I don't think there is anything UWP specific. You will probably have to hack things apart and then sew them back together for it to work.

**Comment by lukasf** [comment]
Closing this, since it is not a lib problem, @mcosmin222 gave some links for you to follow....
