### ISSUE TITLE
Seek issues

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#44]
Has anyone had any weird issues with video seeks on windows build 17134?
I have the following strange behavior with video, with the following pattern:

1) Open video, let it play sequentially for a while, until it reaches an arbitrary position X

2) Attempt to seek backwards to a position before the the point the video played sequentially ( seek position <X)

3) The MediaPlayerElement will now no longer display the video, although sound and subtitles are still displayed correctly.

4) Sometimes, video fast forwards until it gets current position goes back to X.

The same issue does not happen if you seek in the future (i.e seek position > X).

**Comment by mcosmin222** [comment]
It seems that on some files, the seek operation does not reset the timestamp properly.

**Comment by touseefbsb** [comment]
@mcosmin222  any specific file extension where I should try to reproduce the issue? or any specific resolution of the video?

**Comment by mcosmin222** [comment]
.avi is the extension.

**Comment by mcosmin222** [comment]
Well, this happens on ffmpeg 4.0 as well, so it is not ffmpeg, but rather us who are making a mistake somewhere.

Basically, sound and video go out of sync, video freezes until media timeline recovered the seek. If MF still has buffered video data, it will try to fast forward. This may be either our bug or windows bug, but at this point I don't have an older version windows to try on.

**Comment by touseefbsb** [comment]
@mcosmin222  I am able to reproduce the bug in following manner.
play a **.avi** file and then just let it play for a couple minutes naturally, when it reached about 1:46 minutes, ( i min and 46 secs ), then I manually clicked on seekbar to about 1:00 in order to seek it, the seekbar flicked back and then bacme back to 1:46 and the audio kept playing while video frame got stuck.

**Comment by mcosmin222** [comment]
Yes. Exactly  :)

**Comment by touseefbsb** [comment]
I am having some trouble on my virtual machine which is on FCU, my app seems to be stuck on splash screen. I will try to do a debug mode on my VM and try to reproduce this issue there as well once I figure out why my app stucks on splash screen.

**Comment by mcosmin222** [comment]
This seems to be related directly to the video codec. MF reports the proper timestamp, and so does the audio codec. It is weird why the video codec does it.

**Comment by touseefbsb** [comment]
does it has something to do with graphic cards on the device?

**Comment by mcosmin222** [comment]
No. It is a mistake somewhere in the code. I'd guess it is the timestamps.
I did find that at some point after the seek, the video codec outputs a frame with AV_NOPTS_VALUE pts, which defaults to our custom pts calculation, there might be a sneaky bug there. But I am tired now, I will look some more into this the following days.

**Comment by mcosmin222** [comment]
OK I fixed it.

**Comment by touseefbsb** [comment]
which branch is it? if the change is very simple just let me know where to make it, and I will make that change in ffmpeginterop project on my machine and then test it to verify whether it fixes the issue.

**Comment by touseefbsb** [comment]
@mcosmin222  I can confirm with that single change, it fixes the issue.

**Comment by mcosmin222** [comment]
@touseefbsb  Thanks. Now we wait for @lukasf to merge it.

**Comment by lukasf** [comment]
Good job, thanks guys!

I was always wondering why we do all that timestamp fixup stuff, because I never observed a file where this is happening. If all avi files show this "no frame pts" behavior, then this format will be a good test case to check whenever we do bigger changes to the lib.

**Comment by SnowPowerCore** [comment]
I've had this issue with some of .mp4 files too. Seeking for some files was good, for others it was horrible. They stuck on the image for probably 10 sec, and then they turned playback rate to a really high value in order to catch up the sound part. After applying this correction, any file is now seeking as it should be.

**Comment by touseefbsb** [comment]
@SnowPowerCore  good to knw it fixes all files :)

**Comment by mcosmin222** [comment]
@lukasf  I think that in the case of AVI, not all frames have AV_NOPTS_VALUE pts. Some don't, otherwise the fast forwarding noticed by @SnowPowerCore  and I wouldn't have shown valid frames on their way to the sound position. In my case, the video was fast forwarding through frames I knew where there for sure.

I am not 100% convinced if this is a peculiarity of the AVI format (maybe first frame in a package always has AV_NOPTS_VALUE) or it was something ffmpeg was doing internally after seek.

When I first learned how to do media stream sources, I never used the decoder's internal "pts" algorithm for matching things. Always had my manual counting.
