### ISSUE TITLE
mpg and mpeg support?

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#47]
guys do we have mpg and mpeg video files support with this library? I just got a certification rejection from store team for my app, with following notes.

App Policies: 10.1.2 File Extensions

Notes To Developer

The app claims file extension support that it doesn’t provide.  Please remove claims for unsupported file extensions and resubmit the app.

Steps to Reproduce:
1. Launch the app.
2. App opens
3. Commence File extension testing.
4. Notice that the files, mpg, mpeg produce a message, 'To play this video you need a new Codec'.

>Also it would be nice if we can have a list of video and audio extensions this library supports on the readme page?

**Comment by touseefbsb** [comment]
closing this for now because my machine is running mpg files very easily. and I dont know why store is complaining

**Comment by mcosmin222** [comment]
You are probably not using MediaStreamSource to create the mpeg MediaPlaybackItem or you are using hardware decoding for that when creating the FFMpegInteropConfig.

**Comment by touseefbsb** [comment]
@mcosmin222  I just use the default config values of the library I dont specifically change any decoding options, also I am using mediaStreamSource, and as I said I was able to run the files on my machine, store team sometimes complain abt strange things, first they were complaining my app crashes and now I didnt make any change and just re submited a couple times and now they have this new problem instead of crashing :P
