### ISSUE TITLE
no video in some files

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#57]
I noticed that some mkv files cannot show any video but only play the audio. while video can be seen in some other players like vlc.

**Comment by mcosmin222** [comment]
Never seen this.
Do you have a sample file which can reproduce this issue?

**Comment by villagra** [comment]
I've detected also some files that cannot be played... also, I've also seen one where video goes 2x and there is no audio (the windows player, vlc & co play it correctly...)

**Comment by mcosmin222** [comment]
@touseefbsb  please don't post torrent links here unless you are the one who uploaded them (and even so, pirate bay is not the safest place to do it). You can upload the file to onedrive and give a temporary (24h) download link or something.

**Comment by touseefbsb** [comment]
@mcosmin222  here u go this is the sample file u can use to reproduce https://1drv.ms/u/s!ArmYis0SUpsU43BaDzbVGDtTSLmt

**Comment by mcosmin222** [comment]
Ok, I could reproduce the issue with my player. I will see what this is about.

**Comment by mcosmin222** [comment]
I am guessing the fact that the MediaStreamSource doesn't request sample from the video stream is the problem.
I haven't encountered an issue such as this before, and my guess it is a framework bug. I will try to poke at it some more in the following day. There might be some initialization problems somewhere.

**Comment by mcosmin222** [comment]
I can confirm it is a framework bug. Neither Windows Media Player not Movies+TV can play that file.
Only VLC (which I assume uses software decoding) and FFMPEGInterop (considering we disable HEVC passthrough) can do it.

**Comment by mcosmin222** [comment]
Feedback hub link

https://aka.ms/AA1w1t1

**Comment by mcosmin222** [comment]
We could probably work around this by specifically targeting the windows version and bypass consumer decision on the passthrough or remove the HEVC passthrough option until this is fixed.

**Comment by jmvillagra** [comment]
@mcosmin222 yes, it's a mkv file
Here is the test file:

https://we.tl/sQgC9GLrTW

I've seen this problem with quite some files.

**Comment by mcosmin222** [comment]
@jmvillagra your video has the same issue. If you disable the HEVC passthrough in ffmpegconfig, it will play properly ^^.

I suggest you guys issue updates to your apps to fix this until Microsoft gets its act together.

**Comment by jmvillagra** [comment]
Thanks @mcosmin222 
Is it possible to disable the HEVC passthrough somehow via the FFmpegInteropMSS (do you have an example in this case) or it's only a build property when building the FFMpeg project?

Thanks,.

**Comment by mcosmin222** [comment]
There is a FFmpegInteropConfig class that you can pass around. That class has a property for HEVC passthrough (among others).

**Comment by touseefbsb** [comment]
@lukasf  here is the new link for the test file for this issue : https://1drv.ms/v/s!ArmYis0SUpsU7nqp78DRJAMHxb8j

**Comment by lukasf** [comment]
@touseefbsb Your link is the same file as linked in #58. This file works. But I believe for #57 there was a different file (or actually two files, one other shared by @jmvillagra, which is also down now).

**Comment by mcosmin222** [comment]
Hello @touseefbsb 
Would you please reupload the file?

Thanks

**Comment by touseefbsb** [comment]
unfortunately cnt find the exact file now :(

**Comment by lukasf** [comment]
@mcosmin222 Is there a specific reason why you re-opened the issue?

**Comment by mcosmin222** [comment]
@lukasf Yeah, I wanted to test that file again, but I completely forgot about it, had some other issues to deal with
