### ISSUE TITLE
only audio being played on som "mov" video files

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#58]
one of my users emailed me with this issue and I was able to reproduce the issue in my app on my machine, the problem is some video files ( taken from iphone ) when transfered to pc have extension of "mov" and when played in the player just play the audio and not the video, I think this might be related to previously closed issue of "mkv" files? what do u think @mcosmin222  ?
here is the sample file to reproduce : https://1drv.ms/v/s!ArmYis0SUpsU7nqp78DRJAMHxb8j

**Comment by mcosmin222** [comment]
Did you try disabling pass-throughs?

**Comment by touseefbsb** [comment]
No I was not able to test that bcz I dont have my development machine in order at the moment

**Comment by mcosmin222** [comment]
I could not reproduce the bug. File plays fine with my player. With yours, however, it doesn't. So it is something that you are doing wrong.

**Comment by touseefbsb** [comment]
did ur app has disabled pass-throughs?

**Comment by mcosmin222** [comment]
for HEVC, by default, yes. For others the user has options.

**Comment by touseefbsb** [comment]
I did not understand that, I am trying to understand whether this problem is same as previous mkv file? will it be solved if I disable passthroughs? asking it because my app currently doesnt disable passthroughs

**Comment by mcosmin222** [comment]
Yes, if you disable pass-through it should work.
You can test if this is a problem by trying to play the file using one of the Windows built-in players, like movies+TV or Windows Media Player. If you can't play it with these, means file is HEVC.

**Comment by touseefbsb** [comment]
yeah it is not playing properly in movies and tv , thanks for the help, :)

**Comment by mcosmin222** [comment]
Don't forget to send feedback to Microsoft. The latest preview builds all have this problem.

**Comment by touseefbsb** [comment]
@mcosmin222  I think u sent one on mkv issue as well right? plz send me the link so I can comment and upvote on that one.

**Comment by mcosmin222** [comment]
You can find it in the other thread.

**Comment by touseefbsb** [comment]
I think this issue needs to be re-opened with title "mkv" files this time.
here is the sample : https://1drv.ms/u/s!ArmYis0SUpsU_XywSzR92dGhEhhN

**Comment by lukasf** [comment]
@touseefbsb I cannot reproduce. File plays well both with ffmpeg 3.4 and 4.1, with or without passthrough. 

But what I observed: If I use ffmpeg 3.4.2 and a debug build of our lib, I get an access violation + crash when playing the file. In release mode, it plays fine. The same crash does not happen with ffmpeg 4.1. Is this what you have observed or what is your issue?

**Comment by touseefbsb** [comment]
no, actually I am getting no video at all in my app, strange that you cannot reproduce, maybe its difference in graphics card? I am running intel 4000 ( default one on my laptop )

**Comment by touseefbsb** [comment]
btw I am not getting access voilation exception even in debug mode, and I am using ffmpeg build provided to me by @mcosmin222  sometime ago which I think is 3.x

**Comment by touseefbsb** [comment]
I just double checked, same problem is occurring in sample app of this repo as well. I even tested on one of my virtual machines ( 1803 ) and my device ( 1809 ) both showing same problem. my repo is up to date with master, the only issue I suspect is maybe I am using an outdated Build of ffmpeg, I am not sure whether I was supposed to get a newer build of ffmpeg, @mcosmin222  provided me with that build bcz my machine was not able to build it, probably he is using same version of build as me, so maybe he can try to reproduce the issue.

**Comment by lukasf** [comment]
I just found out that This is a HEVC file. Hardware decoding of HEVC has only been added in Skylake CPU (5xxx series), and Windows 10 has no software decoder for HEVC. So if you enable passthrough for HEVC on such a machine, you won't get video.

You can buy HEVC software codec on Windows 10 for 1$:
https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7?activetab=pivot:overviewtab

Or you use free sw decoding in ffmpeg ;)

**Comment by touseefbsb** [comment]
@lukasf  buying the extension will probably help 1 specific user right? But what can I do to ensure that all users of my app get the video ? how can I do free sw decoding of ffmpeg?

**Comment by lukasf** [comment]
You just need to disable HEVC passthrough in the FFmpegInteropConfig object. Then ffmpeg software decoder is used.

**Comment by lukasf** [comment]
The problem is that we currently do not have a way to auto detect if HW decoder is there. So we cannot auto enable passthrough based on HW capabilities. If we enable by default, it causes problems, if we disable by default, we get bad performance on all newer devices.

**Comment by touseefbsb** [comment]
ahan that is really a tricky problem. Thanks for the tip.
