### ISSUE TITLE
I want to add and maintain a branch that uses FFmpegUniversal.

### ISSUE THREAD

**Issue by MouriNaruto** [lukasf/FFmpegInterop#59]
I want to add and maintain a branch that uses FFmpegUniversal (https://github.com/M2Team/FFmpegUniversal).
FFmpegUniversal can make the binary directory of projects that use the FFmpeg library tidy and smaller binaries, because it merges all FFmpeg dynamic link library files in one.
I think if I can provide this branch here, even if it don't be merged into the master branch, it's good news for developers who are pursuing fewer binaries.

What do you think about that? And how to add a branch to this project? @lukasf @mcosmin222 

Mouri

**Comment by lukasf** [comment]
Hi @MouriNaruto! Sure, I just added you as a collaborator. Feel free to create a branch with your build system.

You know I looked into your solution some time back. I like the approach of combining the individual dlls into one. But if I understand correctly, it currently involves multiple build steps. First you need to run the batch file to build the dlls. Then you need to open a sln file in VS and build it (probably multiple times for each platform?). Then you must manually copy that build output to your project.

I had thought about adding this to FFmpegInterop, but in my eyes there is currently too much manual work required to build it. Do you think you can simplify this? I mean, it is not a big deal to build a sln with msbuild. It could be integrated into the build scripts, so running the batch file will automatically create merged dlls for all platforms. If you can optimize it that way, I could even see it in the master branch.

But anyways, adding your current version as a branch won't do any harm.

**Comment by MouriNaruto** [comment]
@lukasf @mcosmin222 Thank you.


FFmpegUniversal uses batch files to build FFmpeg and VS solution to build DLL.
I think I can try to improve the build process.

**Comment by MouriNaruto** [comment]
I created the FFmpegUniversal branch yesterday. (https://github.com/lukasf/FFmpegInterop/tree/FFmpegUniversal)

Today, I have changed the FFmpegUniversal Project. We only need to run the batch file, and it will automatically create merged dlls for all platforms.  You can see the changes in the FFmpegUniversal branch and the FFmpegUniversal project(https://github.com/M2Team/FFmpegUniversal).

@lukasf @mcosmin222 

Mouri.
