### ISSUE TITLE
Extracting video frame fails on some files

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#6]
The error thrown thrown in 
```

return create_task(BitmapEncoder::CreateAsync(encoderGuid, stream)).then([this, pixels, length](task<BitmapEncoder^> encoder)
			{
				auto encoderValue = encoder.get();
				encoderValue->SetPixelData(
					BitmapPixelFormat::Bgra8,
					BitmapAlphaMode::Ignore,
					width,
					height,
					72,
					72,
					ArrayReference<byte>(pixels, length));

				return encoderValue->FlushAsync();
			});
```

WinRT originate error (parameters: 0x88982F8C, 0x00000027, 0x0693D0EC).

the projected error is

Microsoft C++ exception: Platform::COMException ^ at memory location 0x0693CD90. HRESULT:0x88982F8C The buffer allocated is insufficient.
WinRT information: The buffer allocated is insufficient.

I will investigate this more latter, just wanted to let you know about it

**Comment by lukasf** [comment]
I think I already solved that one yesterday, but looks like I did not yet push the changeset. I will check later.

**Comment by lukasf** [comment]
Please try again with latest commit.

**Comment by mcosmin222** [comment]
Nope. That didn't fix it.

**Comment by mcosmin222** [comment]
Indeed it does not seem to have the proper buffer there. The frame size if 1280*720 while the buffer is just 271 bytes. Should have been much bigger than that by my estimates. I wonder if I am hitting on a partial frame inside the video...

**Comment by lukasf** [comment]
For me the problem was that the lib used passthrough. The latest changeset on master branch should have disabled all video passthrough when config->IsFrameGrabber is set. You can step through and check which sample provider is used.

**Comment by mcosmin222** [comment]
Yes, the compressed sample provider is used. I will see what's up, I took the latest code from master.

**Comment by lukasf** [comment]
Could also be a git problem again? Perhaps try to clone lukasf/FFmpegInterop into a new location and check again. At least when I look into the sources, I do not see how this could still happen.

**Comment by mcosmin222** [comment]
Indeed there was a git problem. I am using the filters branch directly into the app, so to get your change i had to rebase/merge the branch with master again, however, for some reason, git didn't apply the changes to ffmpeginterop.cpp file but did so successfully for the video sample provider.
