### ISSUE TITLE
Support UWP applications (xbox,pc,tablet,x86,x64,arm)?

### ISSUE THREAD

**Issue by TheCoder15** [lukasf/FFmpegInterop#68]
Does this Support UWP applications (xbox,pc,tablet,x86,x64,arm)?
can i use it to merge downloaded Audio and video and output an MP4 file?

Thank you

**Comment by lukasf** [comment]
This is UWP and supports all platforms. But like the original lib it does not allow transcoding, only playback and frame grabbing.

**Comment by lukasf** [comment]
There are currently no plans to add transcoding to this lib. So unless you like to add this functionality yourself, you are out of luck.

You could however try to build an UWP compatible version of "ffmpeg.exe" and then call that exe from your UWP app using standard ffmpeg command line API. Please note that this only works on PC using FullTrustProcessLauncher, but not on xbox or other platforms.

**Comment by Krakean** [comment]
@lukasf hopefully you will update your master branch to 4.1 then :)

**Comment by lukasf** [comment]
Working on that. Check PR #45 for progress...

**Comment by mcosmin222** [comment]
Sorry I was away from my PC so I couldn't do it.

**Comment by lukasf** [comment]
@Krakean We now have ffmpeg 4.1 support on master!
