### ISSUE TITLE
vs2015.bat file still exists

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#74]
support for vs 2015 has been dropped but the bat file still exists in the repo as well as the readme indicates the project folder should have 2015 bat file as well

**Comment by lukasf** [comment]
Some people hat problems building ffmpeg with the VS2017 file, if they also had VS2015 installed. For them, building with the old VS2015 file was successful. So I though it is best to leave that file in the repo.

**Comment by touseefbsb** [comment]
ahan makes sense.
