### ISSUE TITLE
 little guide for subs in the readMe?

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#75]
I was wondering can we have some basic guidance regarding how different type of subtitles can be integrated with this library. Using subs in general is a little tricky and confusing in uwp, and this library also deal with media with slightly different set of apis, so it would be great if we can have a very basic level guidance for it in the readme, of how the **Embeded CC** works with the library, and how we the developer can add external ( srt or other subtitle files ) in a playing video.

**Comment by lukasf** [comment]
Yes, maybe some more info could be added on that topic. Basically, all embedded subtitles should work automatically, if you use the MediaPlaybackItem from the CreateMediaPlaybackItem() method, instead of using the old GetMediaStreamSource() method. Embedded subtitles will show up and can be switched in the default transport controls. 

It is also possible to add external subtitle files. Use MediaPlaybackItem.Source to get access to the MediaSource. There you can add external subtitle files. Check this [link ](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-playback-with-mediasource#add-external-timed-text-with-timedtextsource) for more details.

**Comment by touseefbsb** [comment]
I think first we get the mss object with getmediastream method nd then get call the getmediaplaybackitem() method on that mss object to get our playback item. Thanks I will also check out the link you provided.

**Comment by mcosmin222** [comment]
I think there's also a sample from Microsoft which explains subtitles.

**Comment by mcosmin222** [comment]
speaking of subtitles, @lukasf  have you ever seen a format such as this?

{1}{1}25. 000
{147}{221}Previously on "Stargate SG-1":
{232}{289}The exits are sealed, Major.

**Comment by touseefbsb** [comment]
Thanks I will have a look at the sample as well.

**Comment by lukasf** [comment]
@mcosmin222 Do you have a file extension for that format?

**Comment by mcosmin222** [comment]
It was txt. Probably someone uploaded the incorrect extension.

I can upload the entire file when I get home if you wish.

**Comment by mcosmin222** [comment]
Silly me. After a few minutes of search, the format is this

https://en.m.wikipedia.org/wiki/MicroDVD

**Comment by lukasf** [comment]
Oh ok. Then it should be supported by ffmpeg as embedded subtitle. I guess it is not supported as external subtitle through UWP APIs.

It would be great if we could add external subs (and audio) through ffmpeg.

**Comment by mcosmin222** [comment]
Hmm. That's worth a research. I wonder if ffmpeg would identify a sub file as a subtitle through the usual AvCodec API we are using.

**Comment by touseefbsb** [comment]
I think there are also another type of subs : **Image subs** : https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/system-supported-metadata-cues

Maybe it is just me but there seem to be many types of subs, and all of them have a different way of being integrated into the video, which makes it complicated to keep all of them consistent and appear and work together in the same flyout in the transport controls, would it be possible to create a helper in this library for subs? @lukasf  @mcosmin222

**Comment by mcosmin222** [comment]
They are all integrated the same way in the video. Through the timed metadata track object. How you get to that object is the tricker part. But we can't help it. As you noticed, there are a lot of kinds of subtitles, at some point they have to be handled on a case by case basis.

**Comment by lukasf** [comment]
PR is merged, closing this...
