### ISSUE TITLE
VCLibs not compatible with arm

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#77]
was creating app packages and got this error when trying to Build ARM.

> The processor architecture of the project being built "arm" is not supported by the referenced SDK "Microsoft.VCLibs.Desktop, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64".

then I noticed that "Microsoft.VCLibs.Desktop" is referenced in ffmpeginterop project.

**Comment by lukasf** [comment]
We reference VCLibs, not VCLibs.Desktop.
I don't have problems creating ARM or ARM64 packages.

**Comment by touseefbsb** [comment]
interesting my project doesnt reference to Vclibs.Desktop either, I wonder where this reference is coming from, I hve a console project and a class library ( net standard ) for db management as well, but they dnt reference it as well. But closing this bcz it seem the problem is not related to the library.
