### ISSUE TITLE
use Pipelines to improve IO performance

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#80]
not sure if this is helpful to this repo but thought I should atleast reference this new **System.IO.Pipeline** namespace in .Net  as we are doing some stream stuff on the sample app as well as within the ffmpeginterop project maybe this is helpful. More details in the video below.

https://www.youtube.com/watch?time_continue=26&v=1koWtKkKb_o

**Comment by mcosmin222** [comment]
Hi,

System.IO.Pipeline is not available in UWP.
And even if it was, it requires loading the file in memory, which we are trying to avoid.
And even if we had enough memory, it makes no sense to read from disk once, load from memory and then read said memory again before we do decoding.

System.IO.Pipes is a namespace which targets very specific scenarios, such as interprocess communications.

**Comment by lukasf** [comment]
Additionally, we do all decoding and sample related stuff in C++.
No streaming or data handling is done in C# (for good reason).

**Comment by mcosmin222** [comment]
Yeah, and accessing the pipes in C++ is kind of a pain.

**Comment by touseefbsb** [comment]
ahan, understood .

**Comment by mcosmin222** [comment]
Technically, for packaged desktop apps, pipes are available. So you should be able to integrate FFMPEG with those. 
If you feel like it, you can create a sample for integrating FFMPEG interop with such a pipe. It should be an interesting research project.
