### ISSUE TITLE
FFmpeg v4.1 binaries

### ISSUE THREAD

**Issue by pashmak73** [lukasf/FFmpegInterop#84]
Hi, where can I download ffmpeg v4.1 libraries? ARM, ARM64, x86 and x64

I'll be appreciate it, If someone upload it for me.
Thanks

**Comment by mcosmin222** [comment]
You can follow the compilation guide in the readme.md file. This way you can get up to date bins whenever you wish.

**Comment by pashmak73** [comment]
Hi again,
Thanks for answer.
I have VS 2017 v15.9.6. and download ffmpeg and opened `BuildFFmpeg_VS2017.bat` with cmd, everything works fine and creates x86 and x64 libraries for me:
![image](https://user-images.githubusercontent.com/46992431/52367881-59025f00-2a62-11e9-852a-6859fa112e1a.png)
but how can build libraries for ARM and ARM64?

**Comment by lukasf** [comment]
Looks good already, but you might be missing some VS features. The build file should create all platforms, including ARM and ARM64. From VS menu, please open Tools->Get Tools and Features. Open the "Individual Components" tab in the installer, make sure you have checked: 

- C++ Universal Windows Platform tools for ARM64
- Visual C++ compilers and libraries for ARM
- Visual C++ compilers and libraries for ARM64

Having these should allow you to build ARM and ARM64. Please let me know if it works. I might have to add this to the build description of readme.md.

**Comment by pashmak73** [comment]
Never mind, I figure it out how to do it.
Thanks a lot

**Comment by pashmak73** [comment]
@lukasf I tried and still can't build ARM64 libraries. it's only do this:
> 
> 
> @lukasf Thanks, ARM now build successfully, but for ARM64 only creates an folder called `share` which has some `*.c` files(`share/ffmpeg/examples`).
> Is it possible to skip building x86,x64,arm? and only create ARM64?

**Comment by mcosmin222** [comment]
You probably don't have the arm64 compiler installed.

**Comment by pashmak73** [comment]
I've installed these:
```
Win 10 SDK (10.0.17763.0)
Win 10 SDK (10.0.17134.0)
Universal Windows Platform tools
VC++ 2017 version 15.9 v14.16 latest v141 tools
Win 10 SDK (10.0.16299.0) for uwp: c#, vb, js
Win 10 SDK (10.0.16299.0) for uwp: c++
Win 10 SDK (10.0.15063.0) for uwp: c#, vb, js
Win 10 SDK (10.0.15063.0) for uwp: c++
Visual C++ compilers and libraries for ARM64
Visual C++ compilers and libraries for ARM
C++ UWP tools for ARM64
C++ runtime for uwp
C++ runtime for
```
Is there anything that I should install?
I'm using Windows 10 version 1809 build 17763.1

**Comment by lukasf** [comment]
I don't see anything missing there. Please edit the build file, search `:Win10`, on next line put `goto Win10ARM64`. Now it should only try to build ARM64. Run the file and paste output here. The latest build file already supports platform arguments, but it's not ready to merge to master yet.

**Comment by lukasf** [comment]
From the UWP workload optional components, I have also checked "C++ UWP tools", make sure you have this as well.

**Comment by pashmak73** [comment]
Here,
[log.txt](https://github.com/lukasf/FFmpegInterop/files/2845274/log.txt)
I couldn't find `C++ UWP tools`, I only find `C++ uwp tools for ARM64`

**Comment by lukasf** [comment]
Expand the UWP workload on the right panel of the installer (instead of individual components). This is how it looks like in German language:

![screenshot 2 cut](https://user-images.githubusercontent.com/2306201/52481979-5150d080-2bb0-11e9-97b1-704640100f5d.png)

**Comment by lukasf** [comment]
I can't say from the log file what is going wrong. It finds all the dependencies, starts compiling, then at some point compilation fails. The first file it fails with is w64, and it only contains a few simple const definitions, no code at all. 

Do you have enough free disk space? Does it always fail at the same file?

**Comment by lukasf** [comment]
My FFmpegInterop folder is over 6 GB in size with all the temp files...

**Comment by pashmak73** [comment]
It doesn't exists!
![image](https://user-images.githubusercontent.com/46992431/52482530-bfa08d80-2bc6-11e9-8e2d-8ba591d28d58.png)

Free space on my E partition 47GB and for C partition is 7GB
I don't know, every time it will close automatically and I couldn't see whats going on.

**Comment by lukasf** [comment]
I think `UWP Tools für C++` in German is `C++ Universal Windows Platform tools` in English. It's so stupid that they change names in the translation and switch acronyms. So yeah, you have those tools.

Open a new cmd, go to project folder, run the build script. Now console will stay open after the build.

Do you use the ffmpeg version that comes with the repo, or did you clone your own ffmpeg sources?

**Comment by ramtinak** [comment]
debug log: [log.txt](https://github.com/lukasf/FFmpegInterop/files/2847687/log.txt)

and I've downloaded from https://github.com/FFmpeg/FFmpeg (latest master branch) 4 days ago. 
should I test it with [@ 10506de](https://github.com/FFmpeg/FFmpeg/tree/10506de9ad1fb050737ef79cf4853742b793c37d) ?

**Comment by pashmak73** [comment]
debug log: [log.txt](https://github.com/lukasf/FFmpegInterop/files/2847689/log.txt)

and I've downloaded from https://github.com/FFmpeg/FFmpeg (latest master branch) 4 days ago. 
should I test it with [@ 10506de](https://github.com/FFmpeg/FFmpeg/tree/10506de9ad1fb050737ef79cf4853742b793c37d) ?

**Comment by lukasf** [comment]
Oh, you are not supposed to use latest ffmpeg for building. It could contain various issues, it could even have breaking changes to the APIs FFmpegInterop uses. You should always use the ffmpeg version that is included here as submodule, which currently is n4.1. Some of the build errors look like work-in-progress bugs in ffmpeg to me.

If you want to get back to our recommended submodule, try this: Go to ffmpeg folder. Delete all content. Now open git bash in FFmpegInterop root. Type these two commands:

```
git submodule init
git submodule update
```

This should get you to the official ffmpeg repo (which is not on github but self hosted) and n4.1 release.
To verify which release you are on, type this:

```
cd ffmpeg
git status
```

It should show that you currently checked out tag n4.1.

Now you are setup correctly. Whenever the recommended version for FFmpegInterop changes, you just need to type `git submodule update` in git bash and you are back in sync with our recommended version.

If you want to test later versions, you can do so, but please be aware that it can cause unexpected issues. And I'd recommend you only test officially tagged ffmpeg releases. So never checkout latest or dev branches, always checkout based on "n*" release tags.

**Comment by pashmak73** [comment]
@mcosmin222 
@lukasf I forgot to test this till today. I did what said, and now it builds ARM64 too.
Thank you so much .

**Comment by lukasf** [comment]
Glad to hear that it helped. I will update the readme to include those important bits.
