### ISSUE TITLE
FFmpeg 4.1.1

### ISSUE THREAD

**Issue by lukasf** [lukasf/FFmpegInterop#87]
I saw that FFmpeg 4.1.1 was recently released.
We could consider upgrading our ffmpeg submodule to the new release.

**Comment by mcosmin222** [comment]
Is this the one containing the fix for UTF bom?

**Comment by lukasf** [comment]
That one only seems to be on the master branch. I guess we'll have to wait for 4.2 for that one.

**Comment by lukasf** [comment]
I tested FFmpeg 4.1.1. Compiles fine, plays fine, no issues observed so far. I accidentially checked it in on external-subtitles branch. So you can now test it on that branch. Just type:

    git submodule update

and it should put ffmpeg to 4.1.1:

    Submodule path 'ffmpeg': checked out '74700e50bf7444930bfc12935bd3e17cd5f766c1'

I will do some more testing, but so far it looks good.

**Comment by mcosmin222** [comment]
Same here, no issues.

**Comment by lukasf** [comment]
This was merged with subtitles PR. Closing.
