### ISSUE TITLE
Calculating Subtitle x,y coordinate

### ISSUE THREAD

**Issue by pashmak73** [lukasf/FFmpegInterop#88]
Hi, This isn't an issue actually,
But I was wondering to know how do you calculate x,y coordinates of an subtitle.

It seems you get `PlayResX` and `PlayResY` and `\pos(x,y)`.
I tried to do the same with an textblock, with no success, it's very close to real coordinates but it's not match:
here is my code:
```C#
        public int PlayResX { get; set; } = 1280; // for example
        public int PlayResY { get; set; } = 720; // for example
        public Size WindowSize { get; set; } // changes when SizeChanged invoked

        async Task Add(double xX, double yY, string text)
        {
            var x = (xX / PlayResX);
            var y = (yY / PlayResY);

            var textBlock = new TextBlock
            {
                Margin = new Thickness(-500, -500, 0, 0),
                Text = text,
                FontSize = 20,
                VerticalAlignment = VerticalAlignment.Top,
                HorizontalAlignment = HorizontalAlignment.Left,
                Foreground = new SolidColorBrush(Colors.White)
            };
            await Task.Delay(10);
            textBlock.Margin = new Thickness(((x * WindowSize.Width) - ((textBlock.ActualWidth))),
                        ((y * WindowSize.Height) - ((textBlock.ActualHeight))), 0, 0);

            MainGrid.Children.Add(textBlock);
        }
```
example:
```C#
            await Add(188.8, 53.6, "Translated by ");
```

Where am I wrong?

Thanks.

**Comment by mcosmin222** [comment]
You need to normalize against the rendering surface actual size, not the size of the video. In case the rendering surface is not a borderless window, WindowSize will also introduce offsets

**Comment by lukasf** [comment]
And actually, we do not calculate these positions. We pass through the subtitle data to UWP APIs, and let the platform render the subtitles onto the video.

**Comment by lukasf** [comment]
Is there a specific reason why you want to render the subtitles yourself?

**Comment by mcosmin222** [comment]
And I think using Margin to align the position is also wrong. afaik, Margin works with effective pixels, whereas the subtitle will need coordination with higher precision.

**Comment by pashmak73** [comment]
Because my app supports subtitle synchronization and changing default font style (font size, family, style, weight, color, shadow color). 
and I think this can't be possible while I don't have any control of showing subtitle.

Also my app can parse a lot of subtitles and I can't let platform take care of this.

**Comment by mcosmin222** [comment]
But it is much easier to just add an offset to our calculation for sub sync rather than create your entire engine from scratch. 
We also support custom text styles.
As for formats, we are adding new support in the latest PR. I think you are going way overkill.
